name: activity_bloc_example
description: An example of using activity_bloc package
publish_to: none
version: 0.0.17

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  activity_bloc: ^0.0.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.1
  get_it: ^8.0.2

dev_dependencies:
  activity_bloc_builder: ^0.0.17
  build_runner: ">=2.10.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
