name: activity_bloc
description: Easily wrap async functions into blocs to manage their execution states
version: 0.0.17
repository: https://github.com/dsvishchov/activity_bloc
issue_tracker: https://github.com/dsvishchov/activity_bloc/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  bloc: ">=8.0.0 <10.0.0"
  equatable: ^2.0.0
  fpdart: ^1.0.0
  meta: ^1.9.0
