name: activity_bloc_builder
description: A code generator companion for activity_bloc
version: 0.0.13
repository: https://github.com/dsvishchov/activity_bloc
issue_tracker: https://github.com/dsvishchov/activity_bloc/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  activity_bloc: ^0.0.13
  analyzer: ">=8.0.0 <9.0.0"
  build: ">=3.0.0 <5.0.0"
  meta: ^1.9.0
  source_gen: ">=3.0.0 <5.0.0"
